# menuprjt.p65  appele par PROJET
# 3 5 <- respecter le cadrage
# nom de la commande avant !
  1 AXEPROJEt calcul du trace en plan
  2 corriger le fichier trace
  3 TRTN extraction des profils en travers terrain naturel
  4 P58 dessin du profil en long du tn
  5 mise en place des profils projet + cubatures
  6 dessin des profils en travers projet + tn
  7 dessin des profils en travers tn
  8 dessiner le projet sur le plan
  9 restaurer le modele terrain naturel
 10 PLTN extraction du profil en long terrain naturel
 11
 12 ALIGner Points sur n1 n2 n3 ....profil en long (donnees/p58)
 13
 14 interpolation de cotes rondes en Z
 15
 16
 17
 18
 19
 20
