# menutopo.pyt  appele par menutopo
# 3 5 <- respecter le cadrage
# nom de la commande (8 caracteres maxi) avant !
#
  0            fichier MENUTOPO.PYT
  1 translom ! programme de transfert ................
  2            carnet terrain (dans c:\mcg)
  3 p33 ! traitement carnet terrain .............. p33
  0     !     -> carnet pour p34
  5 p34 ! canevas/details XYZ calcul en bloc ..... p34
  0     ! recherche automatique de l'ordre de calcul
  0     ! et des fautes, a partir des observations
  8 p43 ! correction des distances au niveau Zref
  0       et/ou Lambert, avec les Z/XY de chaque point
  9 e   ! editeur de texte
 10 listepyt ! imprimer un fichier ( avec print du
  0               systeme ou autre )
  0
 13 p65 ! dao, calculs geometriques, DXF, surfaces, ..
 13 tracepyt ! dessin sur traceur
 14 p17 ! traitement terrain naturel
 15 p11 ! utilitaires ............................ p11
 16 p40 ! nivellement direct calcul en bloc
  0
 20 p44 ! polygonation triangulation (pts isoles)  p44
