# menucarn.pyt  appele par TRANSFERT
# 3 5 <- respecter le cadrage
# nom de la commande (8 caracteres maxi) avant !
  0            MENUCARN.PYT  
  0     transfert carnets electroniques
  0
  3 tba1     ! geotronics tba1.exe ou nom.exe dans c:\mcg
  4 translom ! topcon  translom.exe dans c:\mcg
  5 tba3     ! wild leica tba3.exe ou gif12.exe
  6 tba4     ! kern       etc...
  7 tba5     ! pentax
  8 tba6     ! nikkon
  9 tba7     ! sokkisha
 10 tba8     ! zeiss
 11 p5       ! test ( utilitaire pytha )
 12          !  ou ...
