MCGPLANS
#NOM_ACAD             PLANBLOC_PYTHA TRAI_PYTHA  PLU_PYTHA   99 maxi
0                       0101           1           2
FA1                     0101           1           4
FAS                     0201           1           4
FAT                     0301           1           4
FB1                     0402           1           5
FB2                     0502           1           5
FB3                     0602           1           5
FB4                     0702           1           5
FB5                     0802           1           5
FBS                     0902           1           5
FBT                     1002           1           5
FC1                     1103           1          15
FD1                     1204           1          15
FDS                     1304           1          15
FDT                     1404           1          15
FE1                     1505           1           9
FES                     1605           1           9
FET                     1705           1           9
FF1                     1806           1          15
FF2                     1906           1          15
FFS                     2006           1          15
FFT                     2106           1          15
FG1                     2207           1           6
FG2                     2307           1           6
FG3                     2407           1           6
FG4                     2507           1           6
FGS                     2607           1           6
FGT                     2707           1           6
FH1                     2808           1           6
FHS                     2908           1           6
FHT                     3008           1           6
FI1                     3109           1           2
FIS                     3209           1           2
FIT                     3309           1           2
FJ1                     3410           1           5
FJS                     3510           1           5
FJT                     3610           1           5
FK1                     3711           1          15
FKS                     3811           1          15
FKT                     3911           1          15
FL1                     4012           1          15
FLS                     4112           1          15
FLT                     4212           1          15
FM1                     4313           1          15
FMS                     4413           1          15
FMT                     4513           1          15
FN1                     4614           1          15
FNS                     4714           1          15
FNT                     4814           1          15
FO1                     4915           1          15
FOS                     5015           1          15
FOT                     5115           1          15
FP1                     5216           1          15
FPS                     5316           1          15
FPT                     5416           1          15


MCGTRAITS               #ne pas modifier
CONTINU         1
CONTINUOUS      1
DISCONTINU      2
CACHE           2


