# A partir du caractere # ( diese ) les donnees sont ignorees par
# les routines d'entree. Utile pour ignorer temporairement certaines
# donnees ...
# Pour avoir diese  sur azerty / compatibles ibm => CTRL ALT 3 ??
# Les caracteres de tabulation dans les donnees sont equivalents a
# un espace.

pARAM.P7
ecritures	# pour valider supprimer # en colonne 1
#commande
#	P     dx/P	dy/P	hx	hy  slant  ang ecriture/ox
stit	HG	30	-16	3.6	4	25	0
tex1	hg	30	-24	3.6	4	0	0
tex3	HG	30	-32	3.6	4	0	0
ktgv	HG	95	-32	3.6	4	0	0
stex	HG	72	-48	3.6	4	0	0
tex2	hg	30	-48	3.6	4	0	0
p	hd	-50	-20	3.6	4	0	0
s	hd	-50	-28	3.6	4	0	0
zpro	hd	-50	-36	3.6	4	0	0
ztn	hd	-50	-44	2.7	3	0	0
tex4	hg	30	-56	3.6	4	0	0
x	HD	-50	-50	2.7	3	0	0
y	hd	-50	-56	2.7	3	0	0
fin
affi,1
fin

para.p12
AFFI,1
FIN
