# menugene.pyt  appele par pyta : 23 lignes maxi  de a … t
# 3 5 <- respecter le cadrage
# nom de la commande (8 caracteres maxi) avant !
  0         MENUGENE.PYT
  1  a  ! creer un dossier
  2     !
  3  b  ! ouvrir un dossier existant
  4     !
  5  h  ! sauver un dossier compresse (?.zip)
  6  d  !  sauver un dossier
  7     !
  8  e  ! restaurer un dossier
  9     !
 10  c  ! effacer un dossier
 11     !
 12  f  ! changer de drive ( a: b: ....)
 13     !
 14  g  ! editer un fichier
 15     !
 16  i  ! saisir les nxyz des points connus
